// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAx4JAQkiwKNl9ZqClOhLGixbVF1yHeoQ',
    appId: '1:323526596679:web:775101df4f72e745103962',
    messagingSenderId: '323526596679',
    projectId: 'anugami-346e8',
    authDomain: 'anugami-346e8.firebaseapp.com',
    databaseURL: 'https://anugami-346e8-default-rtdb.firebaseio.com',
    storageBucket: 'anugami-346e8.firebasestorage.app',
    measurementId: 'G-VMQD02TB38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4n8Cx87sMHJXl_mtGv0l42OudVihr3M8',
    appId: '1:323526596679:android:b5f10e245b326bf0103962',
    messagingSenderId: '323526596679',
    projectId: 'anugami-346e8',
    databaseURL: 'https://anugami-346e8-default-rtdb.firebaseio.com',
    storageBucket: 'anugami-346e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeclJAyoaG934dmKaMwr1Xvfy2_FE_66w',
    appId: '1:323526596679:ios:0763456add2449ad103962',
    messagingSenderId: '323526596679',
    projectId: 'anugami-346e8',
    databaseURL: 'https://anugami-346e8-default-rtdb.firebaseio.com',
    storageBucket: 'anugami-346e8.firebasestorage.app',
    iosBundleId: 'com.example.anuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeclJAyoaG934dmKaMwr1Xvfy2_FE_66w',
    appId: '1:323526596679:ios:0763456add2449ad103962',
    messagingSenderId: '323526596679',
    projectId: 'anugami-346e8',
    databaseURL: 'https://anugami-346e8-default-rtdb.firebaseio.com',
    storageBucket: 'anugami-346e8.firebasestorage.app',
    iosBundleId: 'com.example.anuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApVm_DvMrhXeVWFZt-woN2g4UIxwMd_TE',
    appId: '1:323526596679:web:0e4801136c5ba5f5103962',
    messagingSenderId: '323526596679',
    projectId: 'anugami-346e8',
    authDomain: 'anugami-346e8.firebaseapp.com',
    databaseURL: 'https://anugami-346e8-default-rtdb.firebaseio.com',
    storageBucket: 'anugami-346e8.firebasestorage.app',
    measurementId: 'G-MB7585MJRQ',
  );
}
